_target_: navsim.planning.utils.multithreading.worker_ray_no_torch.RayDistributedNoTorch
_convert_: 'all'
master_node_ip: null    # Set to a master node IP if you desire to connect to cluster remotely
threads_per_node: 32 #null  #128 #null  # Number of CPU threads to use per node, "null" means all threads available
debug_mode: false       # If true all tasks will be executed serially, mainly for testing
log_to_driver: true     # If true, all printouts from ray threads will be displayed in driver
logs_subdir: 'logs'     # Subdirectory to store logs inside the experiment directory
use_distributed: true #false  # Whether to use the built-in distributed mode of ray
#runtime_env:
#        env_vars:
#                ASCEND_RT_VISIBLE_DEVICES: "" 
